services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 7654:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deidb

  mailcrab:
    image: marlonb/mailcrab:latest
    ports:
      - "1080:1080"  # Web interface to view emails
      - "1025:1025"  